delete_datasources:
  - name: Prometheus
    org_id: 1

datasources:
  # <string, required> name of the datasource. Required
- name: PROMETHEUS
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: direct
  # <int> org id. will default to org_id 1 if not specified
  org_id: 1
  # <string> url
  url: http://prometheus:9090
  # <bool> enable/disable basic auth
  basic_auth:
  # <string> basic auth username
  basic_auth_user:
  # <string> basic auth password
  basic_auth_password:
  # <bool> enable/disable with credentials headers
  with_credentials:
  # <bool> mark as default datasource. Max one per org
  is_default: true
  # <map> fields that will be converted to json and stored in json_data
  json_data: {}
  secure_json_data: {}
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false

